### ISSUE TITLE
DNS over TLS does not work with dnsdist 1.4.0-beta1

### ISSUE THREAD

**Issue by paddg** [gryphius/androdns#18] opened 2019-06-04 11:49 UTC
The error message is
`I/O Error: java.io.IOException: could not set up DoT connection: null`

My guess is a TLS certificate validation error.

While certificate validation works for DoH queries, it does not work for DoT queries if there is no certificate for the IP address but only for the Domain Name. Unfortunately it is not possible to purchase certificates for IP addresses from Let’s Encrypt.

"kdig", for example has a switch for this case: `+tls-hostname=STR`

**Comment by gryphius** [comment] 2019-06-04 12:09
not sure this is really related to the certificate. I've tried this with self signed, bare ip, wrong hostname and all work in my case. the `null` error is indeed not very helpful. do you have a public instance where I can debug this?

**Comment by paddg** [comment] 2019-06-05 09:04
Hello Oli, thanks for responding. I have a test setup on 80.156.145.253 where you can try.

**Comment by gryphius** [comment] 2019-06-05 12:13
Ok, with this IP I can replicate the issue. @paddg could you describe the setup of this DoT server? What software is running there?


The underlying exception:
``` 
2019-06-05 14:08:43.977 17502-18288/? W/System.err: java.io.EOFException
2019-06-05 14:08:43.978 17502-18288/? W/System.err:     at java.io.DataInputStream.readFully(DataInputStream.java:200)
2019-06-05 14:08:43.978 17502-18288/? W/System.err:     at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:341)
2019-06-05 14:08:43.978 17502-18288/? W/System.err:     at androdns.android.leetdreams.ch.androdns.SimpleDoTResolver.sendAndReceive(SimpleDoTResolver.java:356)
2019-06-05 14:08:43.978 17502-18288/? W/System.err:     at androdns.android.leetdreams.ch.androdns.SimpleDoTResolver.send(SimpleDoTResolver.java:283)
2019-06-05 14:08:43.978 17502-18288/? W/System.err:     at androdns.android.leetdreams.ch.androdns.DNSFormActivity.doLookup(DNSFormActivity.java:344)
2019-06-05 14:08:43.978 17502-18288/? W/System.err:     at androdns.android.leetdreams.ch.androdns.DNSFormActivity.doLookup(DNSFormActivity.java:444)
2019-06-05 14:08:43.978 17502-18288/? W/System.err:     at androdns.android.leetdreams.ch.androdns.DNSFormActivity$8.run(DNSFormActivity.java:607)
2019-06-05 14:08:43.978 17502-18288/? W/System.err:     at java.lang.Thread.run(Thread.java:764)
```

**Comment by paddg** [comment] 2019-06-05 12:37
It is dnsdist 1.4.0-alpha2 with this configuration:
`addTLSLocal("80.156.145.253:853", {dotpem}, {dotkey})`

**Comment by gryphius** [comment] 2019-06-07 11:24
I'm still trying to debug what's going on here. I'm able to reproduce the issue with your IP, but not with my own dnsdist instances. I can also see that kdig/dnstls  get a reply from your ip and androdns does not, but I haven't  found the problem yet. Currently playing with mitmproxy to capture the queries and hoping to find the difference in the pcaps

**Comment by gryphius** [comment] 2019-06-07 11:53
the problem also happens in jDNSproxy 

```
java -jar jDnsProxy.jar jdns.properties
config:{staleResponseTtl=10, cacheDelayMinutes=60, staleResponseTimeout=1000, listeners=tcp://127.0.0.1:5333 udp://127.0.0.1:5333, cacheFile=dnscache.map, packetQueueLength=100, minTtl=600, connectTimeout=500, resolvers=tls://80.156.145.253:853 }
startup complete
FAILURE: tls://80.156.145.253:853: null
FAILURE: tls://80.156.145.253:853: null
```

**Comment by gryphius** [comment] 2019-06-07 12:05
@paddg do you see anything helpful in the dnsdist log?

**Comment by paddg** [comment] 2019-06-07 12:33
@gryphius I'm afraid I can't help you right now. But I'll be back :) Iirc there was nothing to see in the journal. I'll setup a very simple straight configuration when I'm back. To rule out everything I have in addition. Maybe I can find a point where it works, as you did, and go step by step to find that point where it doesn't work anymore.

**Comment by paddg** [comment] 2019-06-24 11:00
Hello @gryphius, I tried it again with dnsdist 1.4.0-beta1 and a minimal configuration. Same negative result.
> but not with my own dnsdist instances

Can you share your dnsdist configuration?

**Comment by gryphius** [comment] 2019-06-24 11:13
> Can you share your dnsdist configuration?


dnsdist on centos7 
```
dnsdist 1.4.0-beta1.137.master.g0a9e6b9f0 (Lua 5.1.4 [LuaJIT 2.0.4])
Enabled features: dns-over-tls(gnutls openssl) dns-over-https(DOH) dnscrypt fstrm ipcipher libsodium protobuf re2 recvmmsg/sendmmsg snmp systemd

openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017
```

```
setLocal("127.0.0.1")
addLocal("2a02:168:7809:23::100")
addLocal("192.168.23.100")
addACL("127.0.0.1")
addACL("::1")
addACL("2a02:168:7809::/48")
addACL("192.168.23.0/24")
controlSocket("127.0.0.1")
setKey("redacted")
webserver("0.0.0.0:8053", "redacted")
 newServer({address="[2a02:168:7809:23::100]:5300", name="swarm", order=1 })  
newServer({address="[2a02:168:7809:23::90]:5300", name="ut", order=2 }) 
addTLSLocal('127.0.0.1', '/etc/dnsdist/dnsdist.pem', '/etc/dnsdist/dnsdist.key')
addTLSLocal('2a02:168:7809:23::100','/etc/dnsdist/dnsdist.pem', '/etc/dnsdist/dnsdist.key')
addTLSLocal('192.168.23.100', '/etc/dnsdist/dnsdist.pem', '/etc/dnsdist/dnsdist.key')
addDOHLocal('2a02:168:7809:23::100','/etc/dnsdist/dnsdist.pem', '/etc/dnsdist/dnsdist.key')
addDOHLocal('192.168.23.100', '/etc/dnsdist/dnsdist.pem', '/etc/dnsdist/dnsdist.key')
```

**Comment by paddg** [comment] 2019-06-24 11:15
In dnsdist verbose mode I get this errors:
`Got an exception while handling (reading) TCP query from 87.143.15.112:48042: Error reading from TLS connection`

**Comment by paddg** [comment] 2019-06-24 11:19
My test configuration:
```
dnsdist 1.4.0-beta1 (Lua 5.3.4)
Enabled features: dns-over-tls(gnutls openssl) dns-over-https(DOH) dnscrypt ebpf ipcipher libsodium protobuf recvmmsg/sendmmsg systemd
```
```
addLocal( "80.156.145.211:53" )
addTLSLocal( '80.156.145.211:853', {dotpem,doteccpem}, {dotkey,dotecckey} )
addDOHLocal( '80.156.145.211',     {dotpem,doteccpem}, {dotkey,dotecckey} )

newServer{address="8.8.8.8:53"}
newServer{address="1.1.1.1:53"}

setACL({"0.0.0.0/0"})

```

**Comment by paddg** [comment] 2019-06-24 11:22
My dnsdist was built with libh2o-devel-2.2.5

**Comment by gryphius** [comment] 2019-06-24 11:23
I see you're using multiple certs, let me check if I can trigger the issue with that

**Comment by paddg** [comment] 2019-06-24 11:26
I tried it with a single cert now. Fails also.

**Comment by gryphius** [comment] 2019-06-24 11:38
what OS/distro do you run dnsdist on?

**Comment by paddg** [comment] 2019-06-24 11:54
I run Suse SLES 15. I also asked @rgacogne from PowerDNS for help. He requested a pcap capture file. You want that too?

**Comment by rgacogne** [comment] 2019-06-24 13:39
It turns out that this is a bug in dnsdist's 1.4.0 DoT code when the two-bytes size of the query is not in one write but is split over two writes. We actually fixed it while working on a different issue this morning: https://github.com/PowerDNS/pdns/pull/7974/files#diff-0bc4a9fbf9980ff5a860e9bc3020c52bR1045

**Comment by gryphius** [comment] 2019-06-24 13:56
Thanks @rgacogne !   I'm closing this then - @paddg in the unlikely case you still have this issue after updating to a dnsdist version with the above fix, please let me know.

**Closed by gryphius** 2019-06-24 13:56 UTC

**Comment by paddg** [comment] 2019-06-25 06:58
For the record: It works now :-)

Tested with
https://downloads.powerdns.com/releases/dnsdist-1.4.0-beta1.tar.bz2
plus
https://github.com/PowerDNS/pdns/pull/7974.patch
Thanks 
@gryphius and @rgacogne
